### ISSUE TITLE
td.replace(path_to_module) seems to affect other modules...

### ISSUE THREAD

**Issue by stringbeans** [testdouble/quibble#19] opened 2017-11-25 02:04 UTC
In the latest version of quibble (v0.5.3) there seems to be an issue where td.replace is affecting modules totally unrelated to the module i am replacing

for example, our project currently uses Sequelize. In one of our tests we have something like so...

```
import * as td from 'testdouble'
td.replace('../some/module')
import * as Connectors from '../../connectors' //this uses sequelize inside of it
```

and we've found that the test will fail because there are missing dependencies in the sequelize module. Digging further into it, it looks like a dependency in sequelize does not properly get `require`'d in 

im sorry for the lack of repro steps as its been very hard for me to fully understand whats causing this to even create repro steps that dont involve sharing the protected IP on my project :(

This seems to only happen in v0.5.3... downgrading to v0.5.2 fixes the issue

**Comment by searls** [comment] 2017-11-25 02:14
Damn. Thanks for the report. Was really hoping the changes this morning wouldn't have wider implications. If you could you provide a small reproducible example that'd help me sort this out

**Comment by searls** [comment] 2017-11-25 14:16
I sat down this morning and read and re-read your summary and I really don't understand what you're describing. If you can give me anything more to go on, whether it's just more narrative, listings of the broken test & source as-is, an example project, or access to the repo, I'd be more than happy to investigate.

I suspect that the 0.5.3 changes, while definitely fixing (what I perceived to be bugs) will invariably cause some test failures. The hard part is determining whether any tests that start failing after the upgrade were false positives (tests that were passing that should not have been) or whether the changes made in 0.5.3 represented a regression in working behavior.

**Comment by stringbeans** [comment] 2017-11-27 18:33
hey @searls ! i'll try to provide as much detail as i can without stepping on my company's IP policies.. and thank you again for being so active!

here are the first few lines of my test file:

```
import test from 'ava'
import * as td from 'testdouble'
 
const segment = td.replace('../../../../lib/segment') 
import * as Connectors from '../../../../connectors'
```

the test fails when it hits the line where I import the Connectors... Here is the error that is generated:

```
/Users/john/Development/edvisor-io/api-server-v2/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:189
      read: Pooling.createPool({
                    ^
TypeError: Pooling.createPool is not a function
```

After some experimentation, I noticed that if I remove the line in the test file `const segment = td.replace('../../../../lib/segment')` I no longer get the error (although one of my tests failed because of the lack of mocking but thats expected). In fact, I can change that line to call `td.replace` on any library and the error would come back. The sequelize library we use has nothing to do with the lib im trying to mock with `td.replace`, but for some reason it gets affected.

Hopefully that's helpful? Sorry for not being able to provide direct repro steps here :(

**Comment by searls** [comment] 2017-11-27 19:22
Well, that certainly makes what you're describing clearer now. Clearly something quibble is doing is affecting how sequelize loads, in that case

Correct me if my assumptions are off, but I imagine this is happening:

1. `td.replace` is called from the test, triggering quibble to replace `require('module')._load` with its artificial one
2. the test invokes `require('../../../../connectors')`, which in turn invokes `require('sequelize')`
3. The require cache is disabled at this point, so `sequelize` will be completely reloaded from its index point, at which point two things can go wrong:
  1. It's possible that sequelize is somehow depending on itself being cached; Node apps/libs should not assume they will be permanently cached upon subsequent calls to `require` but in practice they are. It's entirely possible that `sequelize` does something to make it unsafe to require multiple times (however, I'm unsure how the 2.5.3 changes are what would have triggered your failure)
  2. It's possible the fake load method (which defers to the original `Module._load` function) is behaving differently now, in such a way as to no longer work for you.

We have a little more to go on now, at least

**Comment by stringbeans** [comment] 2017-11-27 19:27
@searls sounds like your assumptions are pointing in the right direction! thanks!! 👍

**Comment by searls** [comment] 2017-11-29 14:22
I took a stab at reproducing this and failed. When sequelize is loaded twice in a quibbled file and connects to a database, it doesn't blow up.

Can you please pull this down and try to adjust it to match your situation more closely https://github.com/searls/quibble-19-reproduction

**Comment by searls** [comment] 2017-11-29 20:39
Additionally, could you provide the version of Node & sequelize, you're using?

**Comment by sarneeh** [comment] 2018-08-22 21:04
@searls I've encountered the same issue but with different library - `querystring`. Let me introduce a reproduction example:

subject:

```js
const qs = require('querystring');
const dep = require('./dep');

module.exports = () => {
  const escapedString = dep();
  return qs.unescape(escapedString);
};
```

test:

```js
const t = require('tap');
const td = require('testdouble');

const dep = td.replace('./dep');
const subject = require('./subject');

t.test('unescape string', t => {
  td.when(dep()).thenReturn('https:\\/\\/example.com');

  const result = subject();

  t.equals(result, 'https://example.com');
  t.end();
});
```

The result in this example is: `not ok qs.unescape is not a function`. Even if `querystring` exposes an `unescape` function. This gets fixed after removing `td.replace` invocation:

subject:
```js
const qs = require('querystring');

module.exports = (escapedString) => {
  return qs.unescape(escapedString);
};
```

test:
```js
const t = require('tap');

const subject = require('./subject');

t.test('unescape string', t => {
  const result = subject('https:\/\/example.com');

  t.equals(result, 'https://example.com');
  t.end();
});
```

I hope it helps somehow 👍

**Comment by searls** [comment] 2018-08-22 22:10
@sarneeh thanks for providing this reproduction! I don't have time to look at this right away, but I appreciate your work and I'll try to get to this soon

**Comment by searls** [comment] 2018-09-21 13:56
I am still stumped as to what is going on, in part because (while I can replicate @sarneeh's example), I cannot (on Node v10.10.0 and npm v6.4.1) replicate the issue when I'm using a symlinked version of quibble.

Here's a stripped down version of the test:

```js
const td = require('testdouble');

const dep = td.replace('./dep');
const subject = require('./subject');

td.when(dep()).thenReturn('https:\/\/example.com');

const result = subject();

if (result !== 'https://example.com') {
  throw 'lol'
} else {
  console.log('good')
}
```

If I use a symlinked checkout of quibble, I get:

```
good
```

But if I use the installed copy I get:

```
/Users/justin/tmp/wat3/subject.js:6
  return qs.unescape(escapedString);
            ^

TypeError: qs.unescape is not a function
    at module.exports (/Users/justin/tmp/wat3/subject.js:6:13)
    at Object.<anonymous> (/Users/justin/tmp/wat3/test.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```

The diff below shows this (where `ugh` is the copy of quibble pulled down from npm install and `quibble` is the symlinked one):
```
○ ~/tmp/wat3 $ diff -rq node_modules/ugh node_modules/quibble
Only in node_modules/quibble: .git
Only in node_modules/quibble: .gitignore
Files node_modules/ugh/.travis.yml and node_modules/quibble/.travis.yml differ
Only in node_modules/quibble/example: .gitignore
Only in node_modules/quibble/example: node_modules
Only in node_modules/quibble/example: package-lock.json
Only in node_modules/quibble: node_modules
Only in node_modules/quibble: package-lock.json
Files node_modules/ugh/package.json and node_modules/quibble/package.json differ
Only in node_modules/quibble/test/fixtures: a-symlinked-function.js
```

This is making it harder to debug, obviously.

It's almost like Node.js doesn't want me to monkey-patch Module._load

**Comment by lytc** [comment] 2019-01-30 04:38
I'm getting the same issue!
This is the sample code to reproduce:
```js
const td = require('testdouble');
const foo = require('./foo');
const foo2 = require('./foo');

console.log(foo === foo2); // true

td.replace('./bar');

const foo3 = require('./foo');
console.log(foo === foo3); // false ?!?!?
```

**Comment by searls** [comment] 2019-01-30 14:05
Yes, @lytc the above is expected behavior and cannot be fixed by quibble/td.js. 

The only reason `foo` and `foo2` will ever `===` each other (whether they're objects or functions) are when they share the exact same identity. Node.js *does not guarantee this will ever be true*, it's an accident of the fact that Node's module cache is very aggressive and very sticky. It is strongly recommended that applications do not write code that depends on getting an identical object back from `require` upon subsequent calls, since the cache is not guaranteed.

The reason `foo3` does not equal the other two is because when quibble is invoked (as it is when you call `td.replace`), then for the rest of the file listing, the module cache will be ignored. This is to avoid ourselves from caching modules that have been tainted by test doubles.

**Comment by searls** [comment] 2019-01-30 14:06
I'm going to close this for now until an example pops up where someone isn't relying on identity matches from the module cache. I think all of these do, and there's nothing the library can do about it, to my knowledge

**Closed by searls** 2019-01-30 14:06 UTC
